scss_files: 'src/static/styles/**/*.css'
exclude:
    - 'src/static/styles/vendor/**'
    - 'src/static/styles/assets/**'

linters:
    Indentation:
        width: 4
    ColorVariable:
        enabled: false
    IdSelector:
        enabled: false
    ColorKeyword:
        enabled: false
    SelectorDepth:
        max_depth: 4
    PropertySortOrder:
        enabled: false
    PseudoElement:
        enabled: false
    MergeableSelector:
        enable: false
    QualifyingElement:
        enable: false

# CSS specific stuff
    MergeableSelector:
        enabled: false
